### ISSUE TITLE
how do we maintain the server tho ? 

### ISSUE THREAD

**Issue by muhzulzidan** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#243]
it says that it  started at http://127.0.0.1:3001 on gatsby build, but we can't open the server because it is already been terminated by the time the buld stop or finish

**Comment by JimmyBeldone** [comment]
Hey @muhzulzidan 

You can't maintain the server during build, but you don't need to, it automatically opens a browser tab with your bundle's stats.

If you have troubles with the server I suggest you use the `static` mode like this : 

```js
// Your plugins
{
    resolve: 'gatsby-plugin-webpack-bundle-analyser-v2',
    options: {
        analyzerMode: 'static',
    },
},
```

This way it will create a `report.html` inside your `/public` dir, and automatically opens it during build.

Let me know if this solution fits your needs

**Comment by muhzulzidan** [comment]
thx, it works
