### ISSUE TITLE
Default to 'static' when running in Gatsby Cloud

### ISSUE THREAD

**Issue by benrobertsonio** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#288]
Hi! When using gatsby-plugin-webpack-bundle-analyser-v2 with incremental builds in Gatsby Cloud, users encounter this error when using the default config:

```
19:17:49 PM: /usr/src/app/www/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
19:17:49 PM: ^
19:17:49 PM: throw ex;
19:17:49 PM: at listenInCluster (net.js:1365:12)
19:17:49 PM: Error: listen EADDRINUSE: address already in use 127.0.0.1:3001
19:17:49 PM: at Server.setupListenHandle [as _listen2] (net.js:1317:16)
19:17:49 PM: at processTicksAndRejections (internal/process/task_queues.js:85:21)
19:17:49 PM: at doListen (net.js:1502:7)
19:17:49 PM: at emitErrorNT (net.js:1344:8)
19:17:49 PM: code: 'EADDRINUSE',
19:17:49 PM: errno: 'EADDRINUSE',
19:17:49 PM: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  19:17:49 PM: syscall: 'listen',
19:17:49 PM: address: '127.0.0.1',
19:17:49 PM: Emitted 'error' event on Server instance at:
19:17:49 PM: port: 3001
```

It's caused because during incremental builds, the build server actually stays running, and the bundle analyzer server never shuts down.

We generally recommend that people set analyzerMode: 'static' so that the results are accessible for each build without spinning up the server. I'd like to suggest we make this the default config if people are running in gatsby cloud (which we can check with process.env.GATSBY_CLOUD. Any issues with providing a separate default config in this instance?

**Comment by JimmyBeldone** [comment]
Hi,

I changed the default `analyzerMode` for Gatsby Cloud users and updated the doc.
Available in 1.1.16

Let me know if does the trick.

**Comment by benrobertsonio** [comment]
Tested and looks good to me - thanks for the quick resolution @JimmyBeldone!!

**Comment by JimmyBeldone** [comment]
Glad to hear it! My pleasure
