### ISSUE TITLE
warn Plugin gatsby-plugin-webpack-bundle-analyser-v2 is not compatible with your  gatsby version 3.0.3 - It requires gatsby@^2.0.0

### ISSUE THREAD

**Issue by ahmadkhalaf1** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#332]
i get this message when i do npm i

warn Plugin gatsby-plugin-webpack-bundle-analyser-v2 is not compatible with your
 gatsby version 3.0.3 - It requires gatsby@^2.0.0

**Comment by JimmyBeldone** [comment]
Hi,

I updated Gatsby peer dependency and updated other dependencies, 
The warning should be gone in v1.1.21
