### ISSUE TITLE
Gatsby v3: Opening twice after build

### ISSUE THREAD

**Issue by feedm3** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#336]
After upgrading to `gatsby` v3 and `gatsby-plugin-webpack-bundle-analyser-v2` v1.1.21 the report opens twice after a build.

![image](https://user-images.githubusercontent.com/7814926/110608146-3df80100-818c-11eb-8e7d-7ceea8a4f8e1.png)

**Comment by JimmyBeldone** [comment]
Hi,

Did you preserve old Webpack cache during transition to Gatsby v3 ?

I suggest you to run `gatsby clean` and then see if it still opens twice.

Let me know if it worked

**Comment by feedm3** [comment]
You were right, thanks! :)
