### ISSUE TITLE
Error parsing bundle asset ...: no such file

### ISSUE THREAD

**Issue by thecodingwizard** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#343]
On Gatsby 3.2, running this webpack bundle analyzer results in a series of "Error parsing bundle asset" errors:

```
Error parsing bundle asset "D:\Code\test-site\framework.js": no such file
Error parsing bundle asset "D:\Code\test-site\commons.js": no such file
Error parsing bundle asset "D:\Code\test-site\polyfill.js": no such file
Error parsing bundle asset "D:\Code\test-site\component---cache-dev-404-page-js.js": no such file
Error parsing bundle asset "D:\Code\test-site\component---src-pages-index-js.js": no such file
Error parsing bundle asset "D:\Code\test-site\component---src-pages-404-js.js": no such file
Error parsing bundle asset "D:\Code\test-site\_cache_dummy_js.js": no such file
```

It was working on 2.32.

Minimal reproduction: https://github.com/thecodingwizard/webpack-analyzer-bug Just clone the repository and run `yarn develop`. The repository is the latest gatsby starter with webpack bundle analyzer added as a plugin.

**Comment by JimmyBeldone** [comment]
Hi ! 

I quickly looked into it and it's a Webpack 5 compatibility issue with some [Webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) combinations of options.

I tested several combinations, and `devMode: true` option  seems to be the only combination not working with Gatsby v3.

Hopefully it will be fixed soon by [Webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) maintainers, in the meantime this is what I suggest : 

- If you don't really need it when running `gatsby develop`: 
--> Remove `devMode: true` from plugin options. You can visualize the result  running `gatsby build` instead.

- If you need it when running `gatsby develop`: 
--> I suggest you disable analyser and generate a stats file. You can set it up this way in plugin options : 

```js
module.exports = {
    plugins: [
        {
            resolve: 'gatsby-plugin-webpack-bundle-analyser-v2',
            options: {
                analyzerMode: 'disabled',
                devMode: true,
                generateStatsFile: true,
                statsOptions: {
                    source: false,
                },
            },
        },
    ],
};
```
`gatsby-config.js`

This will generate a `stats.json`file at the root of your project. You can visualize this stats with Webpack-bundle-analyzer CLI using this command : `npx webpack-bundle-analyzer ./path/to/stats.json`

If you need to set some options here are the possible options : [https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-cli](https://github.com/webpack-contrib/webpack-bundle-analyzer#options-for-cli)

Let me know if it works for you ;)

**Comment by thecodingwizard** [comment]
Awesome, thanks for looking into this! Your suggestions worked wonderfully for me :)

**Comment by ceboola** [comment]
any news on that topic? getting same on v1.1.22 in dev mode
