### ISSUE TITLE
Gatsby4 support

### ISSUE THREAD

**Issue by MattFanto** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#373]
When I build my project using gatsby@4.0.0 I get

warn Plugin gatsby-plugin-webpack-bundle-analyser-v2 is not compatible with your gatsby version 4.0.0 - It requires gatsby@^3.0.0 || ^2.0.0

From what I see the plugin is working very well with gatsby 4 as well, maybe is just necessary to update peer dependency fields in packaga.json

**Comment by DennisKraaijeveld** [comment]
Probably only need to update peer dependency fields yes. Plugin is working perfect on Gatsby 4!

**Comment by LuisOsta** [comment]
@JimmyBeldone Any updates on when https://github.com/JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2/pull/372 could be merged?

**Comment by JimmyBeldone** [comment]
Hey guys, sorry for the late answer, I was on holidays these past few weeks so no laptop.

I just fixed the gatsby peerDependency and updated webpack-bundle-analyser as well. 

Let me know if it is ok for you

**Comment by LuisOsta** [comment]
@JimmyBeldone Thanks! I hope you had a great vacation!
