### ISSUE TITLE
No matching version found for snyk@^2.0.0 after 1.1.4 upgrade

### ISSUE THREAD

**Issue by bbaker6225** [JimmyBeldone/gatsby-plugin-webpack-bundle-analyser-v2#68]
After version 1.1.4 was released yesterday and our project upgraded to it, all of our builds started failing with the error: `No matching version found for snyk@^2.0.0`. Is this something you think you could take a look at?

**Comment by JimmyBeldone** [comment]
Hey, 

I just released 1.1.5 that fixes the problem

**Comment by JimmyBeldone** [comment]
Builds are done correctly on my projects, I wait for you to confirm before closing the issue

**Comment by bbaker6225** [comment]
That fixed it for us, thank you!
